export class Restaurant {
  // uid: 'r1',
  // name: 'Yaaro Ka Adda',
  // shortName: 'yaarokaAdda',
  // cover: 'assets/bannerImgs/b5.jpg',
  // cuisines: ['Italian', 'Mexican'],
  // rating: 5,
  // deliveryTime: 23,
  // price: 100,
  // distance: 5,
  // deliveryTime: 25,
  // description: 'dd',
  // email: 'DosaPlaza@gmail.com',
  // latitude: 26.1286243,
  // longitude: 91.8012675,
  // uid: 'r1',
  // isClose: true,
  // name: 'DosaPlaza',
  // openTime: '07:00',
  // phone: 6619563867,
  // price: 27,
  // rating: 4.7,
  // shortName: 'stayfit',
  // status: 'open',
  // totalRating: 13,
  constructor(
    public uid: string,
    public name: string,
    public shortName: string,
    public cover: string,
    public cuisines: string[],
    public rating: number,
    public deliveryTime: number,
    public price: number,
    public phone?: number, //optional parameters
    public isClose?: boolean,
    public email?: string,
    public city?: string,
    public description?: string,
    public closeTime?: string,
    public address?: string,
    public distance?: number,
    public latitude?: number,
    public longitude?: number,
    public openTime?: string,
    public status?: string,
    public totalRating?: number
  ) {}
}
